const std = @import("std");
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const git_variant = b.option(bool, "git-variant", "Use the Git application identity") orelse false;
    const command = if (git_variant) "coral-git" else "coral";
    const options = b.addOptions();
    options.addOption(bool, "git_variant", git_variant);
    options.addOption([]const u8, "development_styles", b.pathFromRoot("resources"));
    options.addOption(bool, "test_hooks", b.option(bool, "test-hooks", "Enable isolated native test instrumentation") orelse false);
    const m = b.createModule(.{ .root_source_file = b.path("src/main.zig"), .target = target, .optimize = optimize, .link_libc = true });
    for ([_][]const u8{ "gtk4", "gtksourceview-5", "enchant-2" }) |lib| m.linkSystemLibrary(lib, .{ .use_pkg_config = .force });
    m.addCSourceFile(.{ .file = b.path("src/spelling/pango_words.c"), .flags = &.{"-std=c11"} });
    m.addOptions("build_options", options);
    m.addAnonymousImport("style", .{ .root_source_file = b.path("resources/style.css") });
    const exe = b.addExecutable(.{ .name = command, .root_module = m });
    b.installArtifact(exe);
    b.installFile("resources/coral-dark.xml", b.fmt("share/{s}/styles/coral-dark.xml", .{command}));
    b.installFile("resources/coral-light.xml", b.fmt("share/{s}/styles/coral-light.xml", .{command}));
    const generated = b.addWriteFiles();
    const identity = if (git_variant) "org.aqueous.Coral.Git" else "org.aqueous.Coral";
    inline for (.{ .{ "packaging/org.aqueous.Coral.desktop", "share/applications", "desktop" }, .{ "packaging/org.aqueous.Coral.metainfo.xml", "share/metainfo", "metainfo.xml" } }) |entry| {
        const original = @embedFile(entry[0]);
        const named = std.mem.replaceOwned(u8, b.allocator, original, "org.aqueous.Coral", identity) catch @panic("Out of memory");
        const launcher = if (git_variant) std.mem.replaceOwned(u8, b.allocator, named, "Exec=coral", "Exec=coral-git") catch @panic("Out of memory") else named;
        const binary = if (git_variant) std.mem.replaceOwned(u8, b.allocator, launcher, "<binary>coral</binary>", "<binary>coral-git</binary>") catch @panic("Out of memory") else launcher;
        const title = if (git_variant) std.mem.replaceOwned(u8, b.allocator, binary, "Name=Coral\n", "Name=Coral Git\n") catch @panic("Out of memory") else binary;
        const content = if (git_variant) std.mem.replaceOwned(u8, b.allocator, title, "<name>Coral</name>", "<name>Coral Git</name>") catch @panic("Out of memory") else title;
        const file = generated.add(entry[2], content);
        b.getInstallStep().dependOn(&b.addInstallFile(file, b.fmt("{s}/{s}.{s}", .{ entry[1], identity, entry[2] })).step);
    }
    b.installFile("resources/org.aqueous.Coral.svg", b.fmt("share/icons/hicolor/scalable/apps/{s}.svg", .{identity}));
    const run = b.addRunArtifact(exe);
    if (b.args) |args| run.addArgs(args);
    b.step("run", "Launch Coral").dependOn(&run.step);
    const tm = b.createModule(.{ .root_source_file = b.path("src/tests.zig"), .target = target, .optimize = optimize, .link_libc = true });
    for ([_][]const u8{ "gtk4", "gtksourceview-5", "enchant-2" }) |lib| tm.linkSystemLibrary(lib, .{ .use_pkg_config = .force });
    tm.addCSourceFile(.{ .file = b.path("src/spelling/pango_words.c"), .flags = &.{"-std=c11"} });
    const tests = b.addTest(.{ .root_module = tm });
    b.step("test", "Test file format, revisions, Unicode tokenization and real GIO saves").dependOn(&b.addRunArtifact(tests).step);
    const io = b.addOptions();
    io.addOption(bool, "test_hooks", true);
    io.addOption(bool, "git_variant", false);
    io.addOption([]const u8, "development_styles", b.pathFromRoot("resources"));
    const im = b.createModule(.{ .root_source_file = b.path("src/main.zig"), .target = target, .optimize = optimize, .link_libc = true });
    for ([_][]const u8{ "gtk4", "gtksourceview-5", "enchant-2" }) |lib| im.linkSystemLibrary(lib, .{ .use_pkg_config = .force });
    im.addCSourceFile(.{ .file = b.path("src/spelling/pango_words.c"), .flags = &.{"-std=c11"} });
    im.addOptions("build_options", io);
    im.addAnonymousImport("style", .{ .root_source_file = b.path("resources/style.css") });
    const ie = b.addExecutable(.{ .name = "coral-test", .root_module = im });
    const integration = b.addSystemCommand(&.{ "python3", "tests/native.py", "--binary" });
    integration.addArtifactArg(ie);
    if (b.args) |args| integration.addArgs(args);
    b.step("integration", "Run native Coral workflows in an isolated Wayland session").dependOn(&integration.step);
}
