cursor #e6e0e9
cursor_text_color #cac4d0

foreground            #e6e0e9
background            #141218
selection_foreground  #332d41
selection_background  #cbc2db
url_color             #d0bcff

color0   #16131e
color1   #ff5b85
color2   #c38c00
color3   #9e8bd2
color4   #a380ff
color5   #ff569e
color6   #d17d99
color7   #878391
color8   #595663
color9   #ff5b85
color10  #c38c00
color11  #9e8bd2
color12  #a380ff
color13  #ff569e
color14  #d17d99
color15  #b4b0be
