format = "$directory$git_branch$git_status$character"
[directory]
style = "bold #6750a4"
[git_branch]
style = "#7e5260"
[character]
success_symbol = "[❯](bold #6750a4)"
error_symbol = "[❯](bold #8c1d18)"
