[colors]
background = '#fdf7ff'
foreground = '#1d1b20'

cursor_bg = '#6750a4'
cursor_fg = '#fdf7ff'
cursor_border = '#6750a4'

selection_bg = '#eaddff'
selection_fg = '#1d1b20'

ansi = ['#b4b0be', '#ff5b85', '#c38c00', '#9e8bd2', '#a380ff', '#ff569e', '#d17d99', '#433f4c']
brights = ['#706c7a', '#ff5b85', '#c38c00', '#9e8bd2', '#a380ff', '#ff569e', '#d17d99', '#16131e']
