#!/usr/bin/env python3
"""Audit the helper schema against Pearl's generic GTK editors."""
import argparse, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--snapshot',type=Path,default=ROOT/'tests/fixtures/aqueous-master/snapshot.json')
args=p.parse_args();snapshot=json.loads(args.snapshot.read_text())
types={'boolean':'checkbox','integer':'integer spin control','double':'decimal spin control','string':'text entry','string_list':'comma-separated entry','select':'schema choices','color':'color text entry'}
pages={'appearance':'Appearance','layouts':'Layouts','input':'Input','keybinds':'Keybindings','rules':'Rules','displays':'Displays'}
rows=[];seen=set()
for field in snapshot['fields']:
    assert field['id'] not in seen,field['id'];seen.add(field['id'])
    control=types[field['type']];page=pages[field['category']]
    if field['category']=='keybinds' and field['type']=='string_list':control+=' + inhibited recorder'
    scope='native preview required; hardware gated' if field['category']=='displays' else 'edit/validate; apply requires classified impact'
    rows.append(f'| `{field["id"]}` | {page} | {control} | `{field["file"]}` | {scope} |')
header=f'''# Aqueous field/editor coverage

Generated by `scripts/aqueous-inventory.py` from the private helper snapshot in
`tests/fixtures/aqueous-master/snapshot.json`: protocol {snapshot['protocol']}, helper
{snapshot['helper_version']}, **{len(rows)} unique fields**. The script fails for an
unmapped field type/category. GTK renders the current schema, including fields
marked advanced; this table audits the tested schema rather than freezing it.
See [AQUEOUS_SETTINGS.md](AQUEOUS_SETTINGS.md) for workflows and safety gates.

| Field | GTK page | Control | Canonical file | Coverage |
| --- | --- | --- | --- | --- |
'''
footer='''
## Non-scalar coverage

The scalar count is not a claim of complete compositor coverage. See the
[complete capability inventory](AQUEOUS_CAPABILITY_COVERAGE.md), including source,
consumer, UI/CLI entry point and test owner for every contract.

| Collection | Pearl editor | Actual master limits |
|---|---|---|
| Display state | Connected/disabled outputs, actual versus inherited values, source/declaration/identity/mode/support inventories | Canonical observation; no local precedence inference |
| Monitor changes | Position, scale, rotation, mode and mirroring | Compositor-owned lease; physical preview remains unavailable |
| Enablement, primary, profiles, matching, HDR/VRR | Full observation and disabled controls with reasons; Advanced raw draft | Structured helper mutation missing; raw saves still require classified impact and native preview |
| Window rules | Schema fields, inheritance, add/update/delete and ordered move | Helper validates collections but currently reports unknown impact; Pearl blocks save |
| Custom shortcuts | Chord/command fields, recording, add/update/delete | Same classifier dependency; commands never execute during editing |
| Snap layouts/zones | Named layouts, names/padding/default, normalized zone geometry and order; legacy zone controls | Same classifier dependency; optional canvas not implemented |
| Font/cursor synchronization | Scalar controls, explicit sync flags and per-target outcomes | Structured save, reload and toolkit results remain separate |
| Six raw files and complete JSON request | Shared retained Advanced draft | Unknown impact is blocked, including extensions; no raw path bypasses protection |

[Remaining upstream dependencies](AQUEOUS_MASTER_DEPENDENCIES.md) explains the
required helper mutations, collection classification and physical preview work.
'''
(ROOT/'docs/AQUEOUS_FIELD_INVENTORY.md').write_text(header+'\n'.join(rows)+'\n'+footer)
print(f'PASS {len(rows)} fields mapped; collection and raw limits recorded')
