#!/usr/bin/env python3
"""Audit the helper schema against Pearl's generic GTK editors."""
import argparse, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--snapshot',type=Path,default=ROOT/'artifacts/t11/verification/schema.json')
args=p.parse_args();snapshot=json.loads(args.snapshot.read_text())
types={'boolean':'checkbox','integer':'integer spin control','double':'decimal spin control','string':'text entry','string_list':'comma-separated entry','select':'schema choices','color':'color text entry'}
pages={'appearance':'Appearance','layouts':'Layouts','input':'Input','keybinds':'Keybindings','rules':'Rules','displays':'Displays'}
rows=[];seen=set()
for field in snapshot['fields']:
    assert field['id'] not in seen,field['id'];seen.add(field['id'])
    control=types[field['type']];page=pages[field['category']]
    if field['category']=='keybinds' and field['type']=='string_list':control+=' + inhibited recorder'
    scope='draft/validate; policy apply gated' if field['category']=='displays' else 'edit/validate/apply'
    rows.append(f'| `{field["id"]}` | {page} | {control} | `{field["file"]}` | {scope} |')
header=f'''# Aqueous field/editor coverage

Generated by `scripts/aqueous-inventory.py` from the private helper snapshot in
`artifacts/t11/verification/schema.json`: protocol {snapshot['protocol']}, helper
{snapshot['helper_version']}, **{len(rows)} unique fields**. The script fails for an
unmapped field type/category. GTK renders the current schema, including fields
marked advanced; this table audits the tested schema rather than freezing it.
See [AQUEOUS_SETTINGS.md](AQUEOUS_SETTINGS.md) for workflows and safety gates.

| Field | GTK page | Control | Canonical file | Coverage |
| --- | --- | --- | --- | --- |
'''
footer='''
## Collection and raw coverage

| Inventory | Current editor | Explicit limits/deferred work |
| --- | --- | --- |
| Configured/live monitors | Per-display position, scale, rotation and mode controls; `monitor_changes` JSON | Independent preview for connected/enabled displays; no mirror, HDR, VRR, primary, EDID matching, profile, enable/disable or custom-mode editing through the protected path |
| Custom keybindings | Readable inventory; `custom_keybind_changes` add/update/delete request editor | Dedicated visual row editor deferred; `spawn:`/`builtin:` commands retain helper semantics |
| Window rules | Readable inventory; `window_rule_changes` add/update/delete/move request editor | Visual rule builder deferred; move is a separate operation |
| Snap zones/layouts | Readable inventories; `snap_zone_changes`, `snap_layouts`, `default_snap_layout` request editor | Drag-and-drop canvas deferred |
| Stacking aliases | `normalize_stacking` request flag | No raw layout overlap |
| Cursor/font target synchronization | Schema fields, expandable per-target reports, `sync_cursor` / `sync_typography` flags | No old frontend/shell-specific appearance adapter |
| wm/layout/input/outputs/rules/appearance | Six retained raw buffers via file selector; full request JSON | Raw outputs apply is gated; changing raw wm with legacy output/display sections is conservatively gated, including headers inside comments/multiline strings that look like sections |
| Other wm actions/gestures/exec and unknown fields | Raw wm editing when no output/display sections are present | Dedicated structured editors deferred; unknown fields are preserved by the helper |

The helper's 30 window-rule value keys are exposed through `values` in the
request editor: `app_id`, `class`, `title`, `content_type`, `layout`, `output`,
`workspace`, `floating`, `fullscreen`, `ignore_struts`, `width`, `height`, `x`,
`y`, `placement_policy`, `anchor`, `size`, `scale`, `blur`, `opacity`,
`buffer_scale_policy`, `hdr_expand`, `overlay_plane`, `stack_layer`, `focus`,
`fixed_position`, `skip_switcher`, `skip_taskbar`, `scrolling_full_width`, `tag`.

Output enabled/HDR/VRR/profile fields exist in the compositor but are absent from
the helper's monitor projection. Pearl cannot prove a raw edit to those fields
safe, so raw output changes are blocked before save. The legacy wm filter is a
conservative section-name deny list, not a second TOML parser/serializer.
'''
(ROOT/'docs/AQUEOUS_FIELD_INVENTORY.md').write_text(header+'\n'.join(rows)+'\n'+footer)
print(f'PASS {len(rows)} fields mapped; collection and raw limits recorded')
