#!/usr/bin/env python3
"""Regenerate libpulse declarations in a fresh local cache and verify pinned bytes."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--update', action='store_true', help='record the generated hash after an intentional reviewed update')
args = parser.parse_args()
directory = ROOT / 'bindings/headers'
manifest_path = directory / 'inputs.json'
manifest = json.loads(manifest_path.read_text())
for name, expected in manifest['headers'].items():
    actual = hashlib.sha256((directory / name).read_bytes()).hexdigest()
    if actual != expected:
        raise SystemExit(f'{name}: input changed; review source and update its pin explicitly')
env = dict(os.environ, ZIG_GLOBAL_CACHE_DIR=str(ROOT / '.cache/zig'))
with tempfile.TemporaryDirectory(prefix='pearl-bindings-') as tmp:
    prefix = Path(tmp) / 'out'
    subprocess.run(['zig', 'build', 'generate-pulse', '--cache-dir', str(Path(tmp) / 'cache'),
                    '--prefix', str(prefix), '-Doptimize=ReleaseSafe'], cwd=ROOT, env=env, check=True)
    digest = hashlib.sha256((prefix / 'share/pearl/bindings/pulse.zig').read_bytes()).hexdigest()
if args.update:
    manifest['generated_sha256'] = digest
    manifest_path.write_text(json.dumps(manifest, indent=2)+'\n')
elif digest != manifest.get('generated_sha256'):
    raise SystemExit(f'generated bytes changed: {digest}; review before using --update')
print(f'PASS libpulse binding inputs and generated SHA-256 {digest}')
