// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#ifndef __BINDINGS_PLUGIN_H
#define __BINDINGS_PLUGIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct plugin_string_t {
  uint8_t*ptr;
  size_t len;
} plugin_string_t;

typedef uint8_t pearl_plugin_types_node_kind_t;

#define PEARL_PLUGIN_TYPES_NODE_KIND_LABEL 0
#define PEARL_PLUGIN_TYPES_NODE_KIND_BUTTON 1
#define PEARL_PLUGIN_TYPES_NODE_KIND_IMAGE 2

typedef struct pearl_plugin_types_node_t {
  uint32_t   id;
  pearl_plugin_types_node_kind_t   kind;
  plugin_string_t   text;
  plugin_string_t   asset;
  plugin_string_t   clip;
} pearl_plugin_types_node_t;

typedef struct {
  pearl_plugin_types_node_t *ptr;
  size_t len;
} pearl_plugin_types_list_node_t;

typedef struct pearl_plugin_types_scene_t {
  pearl_plugin_types_list_node_t   nodes;
} pearl_plugin_types_scene_t;

typedef struct pearl_plugin_types_setting_t {
  plugin_string_t   key;
  plugin_string_t   value;
} pearl_plugin_types_setting_t;

typedef uint8_t pearl_plugin_types_event_kind_t;

#define PEARL_PLUGIN_TYPES_EVENT_KIND_ACTIVATE 0
#define PEARL_PLUGIN_TYPES_EVENT_KIND_CLICK 1
#define PEARL_PLUGIN_TYPES_EVENT_KIND_TIMER 2
#define PEARL_PLUGIN_TYPES_EVENT_KIND_SETTINGS 3
#define PEARL_PLUGIN_TYPES_EVENT_KIND_DEACTIVATE 4
#define PEARL_PLUGIN_TYPES_EVENT_KIND_ACTIVITY 5
#define PEARL_PLUGIN_TYPES_EVENT_KIND_PREVIEW 6

typedef struct {
  pearl_plugin_types_setting_t *ptr;
  size_t len;
} pearl_plugin_types_list_setting_t;

typedef struct pearl_plugin_types_event_t {
  pearl_plugin_types_event_kind_t   kind;
  uint32_t   node;
  uint32_t   count;
  pearl_plugin_types_list_setting_t   settings;
  bool   reduced_motion;
} pearl_plugin_types_event_t;

typedef pearl_plugin_types_scene_t pearl_plugin_host_scene_t;

typedef uint8_t pearl_plugin_host_availability_t;

#define PEARL_PLUGIN_HOST_AVAILABILITY_AVAILABLE 0
#define PEARL_PLUGIN_HOST_AVAILABILITY_PERMISSION_DENIED 1
#define PEARL_PLUGIN_HOST_AVAILABILITY_UNSUPPORTED 2
#define PEARL_PLUGIN_HOST_AVAILABILITY_SUSPENDED 3

typedef struct {
  bool is_err;
  union {
    plugin_string_t err;
  } val;
} pearl_plugin_host_result_void_string_t;

typedef pearl_plugin_types_event_t exports_pearl_plugin_guest_event_t;

typedef struct {
  bool is_err;
  union {
    plugin_string_t err;
  } val;
} exports_pearl_plugin_guest_result_void_string_t;

// Imported Functions from `pearl:plugin/host@0.1.0`
extern bool pearl_plugin_host_publish(pearl_plugin_host_scene_t *value, plugin_string_t *err);
extern void pearl_plugin_host_log(plugin_string_t *message);
extern bool pearl_plugin_host_set_timer(uint32_t milliseconds, plugin_string_t *err);
extern pearl_plugin_host_availability_t pearl_plugin_host_input_activity(bool subscribe);

// Exported Functions from `pearl:plugin/guest@0.1.0`
bool exports_pearl_plugin_guest_handle_event(exports_pearl_plugin_guest_event_t *value, plugin_string_t *err);

// Helper Functions

void pearl_plugin_types_node_free(pearl_plugin_types_node_t *ptr);

void pearl_plugin_types_list_node_free(pearl_plugin_types_list_node_t *ptr);

void pearl_plugin_types_scene_free(pearl_plugin_types_scene_t *ptr);

void pearl_plugin_types_setting_free(pearl_plugin_types_setting_t *ptr);

void pearl_plugin_types_list_setting_free(pearl_plugin_types_list_setting_t *ptr);

void pearl_plugin_types_event_free(pearl_plugin_types_event_t *ptr);

void pearl_plugin_host_scene_free(pearl_plugin_host_scene_t *ptr);

void pearl_plugin_host_result_void_string_free(pearl_plugin_host_result_void_string_t *ptr);

void exports_pearl_plugin_guest_event_free(exports_pearl_plugin_guest_event_t *ptr);

void exports_pearl_plugin_guest_result_void_string_free(exports_pearl_plugin_guest_result_void_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void plugin_string_set(plugin_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void plugin_string_dup(plugin_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void plugin_string_free(plugin_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
