// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#include "plugin.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `pearl:plugin/host@0.1.0`

__attribute__((__import_module__("pearl:plugin/host@0.1.0"), __import_name__("publish")))
extern void __wasm_import_pearl_plugin_host_publish(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("pearl:plugin/host@0.1.0"), __import_name__("log")))
extern void __wasm_import_pearl_plugin_host_log(uint8_t *, size_t);

__attribute__((__import_module__("pearl:plugin/host@0.1.0"), __import_name__("set-timer")))
extern void __wasm_import_pearl_plugin_host_set_timer(int32_t, uint8_t *);

__attribute__((__import_module__("pearl:plugin/host@0.1.0"), __import_name__("input-activity")))
extern int32_t __wasm_import_pearl_plugin_host_input_activity(int32_t);

// Exported Functions from `pearl:plugin/guest@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_pearl:plugin/guest@0.1.0#handle-event")))
void __wasm_export_exports_pearl_plugin_guest_handle_event_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void pearl_plugin_types_node_free(pearl_plugin_types_node_t *ptr) {
  plugin_string_free(&ptr->text);
  plugin_string_free(&ptr->asset);
  plugin_string_free(&ptr->clip);
}

void pearl_plugin_types_list_node_free(pearl_plugin_types_list_node_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    pearl_plugin_types_node_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      pearl_plugin_types_node_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void pearl_plugin_types_scene_free(pearl_plugin_types_scene_t *ptr) {
  pearl_plugin_types_list_node_free(&ptr->nodes);
}

void pearl_plugin_types_setting_free(pearl_plugin_types_setting_t *ptr) {
  plugin_string_free(&ptr->key);
  plugin_string_free(&ptr->value);
}

void pearl_plugin_types_list_setting_free(pearl_plugin_types_list_setting_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    pearl_plugin_types_setting_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      pearl_plugin_types_setting_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void pearl_plugin_types_event_free(pearl_plugin_types_event_t *ptr) {
  pearl_plugin_types_list_setting_free(&ptr->settings);
}

void pearl_plugin_host_scene_free(pearl_plugin_host_scene_t *ptr) {
  pearl_plugin_types_scene_free(ptr);
}

void pearl_plugin_host_result_void_string_free(pearl_plugin_host_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    plugin_string_free(&ptr->val.err);
  }
}

void exports_pearl_plugin_guest_event_free(exports_pearl_plugin_guest_event_t *ptr) {
  pearl_plugin_types_event_free(ptr);
}

void exports_pearl_plugin_guest_result_void_string_free(exports_pearl_plugin_guest_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    plugin_string_free(&ptr->val.err);
  }
}

void plugin_string_set(plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void plugin_string_dup(plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_free(plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool pearl_plugin_host_publish(pearl_plugin_host_scene_t *value, plugin_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_pearl_plugin_host_publish((uint8_t *) ((*value).nodes).ptr, ((*value).nodes).len, ptr);
  pearl_plugin_host_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

void pearl_plugin_host_log(plugin_string_t *message) {
  __wasm_import_pearl_plugin_host_log((uint8_t *) (*message).ptr, (*message).len);
}

bool pearl_plugin_host_set_timer(uint32_t milliseconds, plugin_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_pearl_plugin_host_set_timer((int32_t) (milliseconds), ptr);
  pearl_plugin_host_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

pearl_plugin_host_availability_t pearl_plugin_host_input_activity(bool subscribe) {
  int32_t ret = __wasm_import_pearl_plugin_host_input_activity(subscribe);
  return ret;
}

__attribute__((__export_name__("pearl:plugin/guest@0.1.0#handle-event")))
uint8_t * __wasm_export_exports_pearl_plugin_guest_handle_event(int32_t arg, int32_t arg0, int32_t arg1, uint8_t * arg2, size_t arg3, int32_t arg4) {
  exports_pearl_plugin_guest_event_t arg5 = (pearl_plugin_types_event_t) {
    (pearl_plugin_types_event_kind_t) arg,
    (uint32_t) (uint32_t) (arg0),
    (uint32_t) (uint32_t) (arg1),
    (pearl_plugin_types_list_setting_t) (pearl_plugin_types_list_setting_t) { (pearl_plugin_types_setting_t*)(arg2), (arg3) },
    (bool) arg4,
  };
  exports_pearl_plugin_guest_result_void_string_t ret;
  plugin_string_t err;
  ret.is_err = !exports_pearl_plugin_guest_handle_event(&arg5, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const plugin_string_t *payload6 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload6).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload6).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_plugin(void);
__attribute__((used))
void __component_type_object_force_link_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_plugin();
}
